# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grH5rt1lJjdklY52f-l3lVwPibc_Bd5A
"""

import requests
from bs4 import BeautifulSoup

def get_survey_numbers(district, mandal, village):
    # Send HTTP request to the website
    url = 'https://dharani.telangana.gov.in/knowLandStatus'
    response = requests.get(url)

    # Parse HTML content
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract dropdown options
    options = {}
    for dropdown in soup.find_all('select'):
        dropdown_id = dropdown.get('id')
        if dropdown_id:
            dropdown_options = []
            for option in dropdown.find_all('option'):
                value = option.get('value')
                if value:
                    dropdown_options.append(value)
            options[dropdown_id] = dropdown_options

    # Simulate user input by sending POST requests
    payload = {
        'district': district,
        'mandal': mandal,
        'village': village,
    }
    response = requests.post(url, data=payload)

    # Parse HTML content after selection
    soup = BeautifulSoup(response.content, 'html.parser')

    print(soup)

    # Extract survey numbers using the correct ID
    survey_numbers = []
    for option in soup.find('select', id='surveyIdselect').find_all('option'):
        survey_numbers.append(option.get('value'))

    # Print survey numbers
    print("Survey Numbers:")
    for survey_number in survey_numbers:
        print(survey_number)

# Example usage
district = 'Nirmal|నిర్మల్'
mandal = 'Soan|సోన్'
village = 'Soan|సోన్'

get_survey_numbers(district, mandal, village)

